version: "3.8"
services:
  servidor:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/js/react/jls-Dockerfile
      args: 
        - CONTEXT=${CONTEXTO}
        - TZ=${TZ}
        - PROYECTO=${PROYECTO}
        - AUTOR=${AUTOR}
        - GITHUB=${GITHUB}
    image: ${AUTOR}/pokeapi
    container_name: ${PROYECTO}
    hostname: ${HOSTNAME}
    env_file:
      - ./.env
    environment:
      - USUARIO=${USUARIO}
      - PASSWORD=${PASSWD}
    ports:
      - "${PORT_ORIGEN}:80"
      - "3002:3000"
    volumes:
    - ./logs:/root/logs
    - ./html:/var/www/html
    networks:
      netcaronte:
        ipv4_address: 172.120.10.5


networks:
  netcaronte:
    ipam:
      driver: default
      config:
        - subnet: 172.120.10.0/24