apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi-kube
  namespace: default
spec:
  replicas: 1 # Número de réplicas
  selector:
    matchLabels:
      app: pokeapi-kube
  template:
    metadata:
      labels:
        app: pokeapi-kube
    spec:
      containers:
        - name: pokeapi-kube
          image: txus027/pokeapi
          env:
            - name: USUARIO
              value: "juanlu"
            - name: PROYECTO
              value: "Pokeapi"
            - name: GITHUB
              value: "https://github.com/Txus27/Pokeapi.git"